#!/usr/bin/env bash
# Improvement: when this machine is the Sunshine server, the side buttons of
# the CLIENT's mouse (Moonlight) don't arrive as buttons but as keys (e.g.
# Solaar turns them into Ctrl+Alt+Left/Right). This improvement binds those
# keys to the same scripts as mouse-forward-back, without touching the
# physical mouse binds (mouse:275 / mouse:276), which stay separate.
set -euo pipefail

DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
# shellcheck source=../../lib/common.sh
source "$DIR/../../lib/common.sh"

NAME="sunshine-mouse-buttons"
CONF_FILE="$MGLDVD_STATE_DIR/${NAME}.conf"
LUA_FILE="$MGLDVD_HYPR_DIR/${NAME}.lua"
# Script generated by the mouse-forward-back improvement (reused as is).
MOVE_SCRIPT="$MGLDVD_STATE_DIR/mouse-forward-back-move.sh"

defaults() {
  # Keys the client sends. LEFT moves focus to the column on the left (and,
  # with a double click at the edge, to the previous workspace); RIGHT does
  # the same toward the right.
  LEFT_KEY="CTRL + ALT + Left"
  RIGHT_KEY="CTRL + ALT + Right"
}

load_conf() {
  defaults
  # shellcheck disable=SC1090
  [ -f "$CONF_FILE" ] && source "$CONF_FILE"
  return 0
}

save_conf() {
  common::ensure_state_dir
  cat >"$CONF_FILE" <<EOF
LEFT_KEY="$LEFT_KEY"
RIGHT_KEY="$RIGHT_KEY"
EOF
}

# The keys are written inside a Lua string: only safe characters are accepted
# so odd input can't break bindings.lua.
valid_key() { [[ "$1" =~ ^[A-Za-z0-9_]+( \+ [A-Za-z0-9_]+)*$ ]]; }

check_keys() {
  local key
  for key in "$LEFT_KEY" "$RIGHT_KEY"; do
    if ! valid_key "$key"; then
      echo "Invalid key: '$key'. Use Hyprland's format, e.g. 'CTRL + ALT + Left'." >&2
      return 1
    fi
  done
  if [ "$LEFT_KEY" = "$RIGHT_KEY" ]; then
    echo "The left and right keys can't be the same." >&2
    return 1
  fi
}

render() {
  common::ensure_mgldvd_dir
  cat >"$LUA_FILE" <<EOF
-- Generated by omarchy-mgldvd (improvement: ${NAME}).
-- Do not edit this file by hand: use "./run" in the omarchy-mgldvd repo
-- to adjust the keys.
o.bind("${LEFT_KEY}", "Previous column via Sunshine/Moonlight (double click at the edge = previous workspace)", "${MOVE_SCRIPT} forward")
o.bind("${RIGHT_KEY}", "Next column via Sunshine/Moonlight (double click at the edge = next workspace)", "${MOVE_SCRIPT} back")
EOF
}

cmd_name() { echo "Sunshine: client mouse back/forward buttons (arrive as keys)"; }

cmd_description() {
  load_conf
  echo "The keys ${LEFT_KEY} / ${RIGHT_KEY} (sent by the client, e.g. via Solaar) switch columns just like mouse-forward-back. Doesn't touch the physical mouse buttons. Requires the mouse-forward-back improvement to be installed."
}

cmd_status() {
  if [ -f "$LUA_FILE" ] && common::require_block_present "$NAME"; then
    echo "installed"
  else
    echo "not-installed"
  fi
}

cmd_install() {
  load_conf
  if [ ! -x "$MOVE_SCRIPT" ]; then
    echo "The 'mouse-forward-back' improvement is missing (it generates $MOVE_SCRIPT). Install it first." >&2
    exit 1
  fi
  check_keys
  render
  common::add_require_block "$NAME"
  save_conf
  common::reload_hyprland
  echo "Installed: ${LEFT_KEY} = left, ${RIGHT_KEY} = right."
}

cmd_uninstall() {
  common::remove_require_block "$NAME"
  rm -f "$LUA_FILE"
  common::reload_hyprland
  echo "Uninstalled. The physical mouse buttons were not touched."
}

cmd_configure() {
  load_conf
  echo "Hyprland format, e.g. 'CTRL + ALT + Left'. They must match the keys the client sends."
  echo "To see them: on this machine, run 'wev' or 'cat -v' while the client presses the button."
  if command -v gum >/dev/null 2>&1; then
    LEFT_KEY=$(gum input --value "$LEFT_KEY" --header "Key that moves left")
    RIGHT_KEY=$(gum input --value "$RIGHT_KEY" --header "Key that moves right")
  else
    read -r -p "Left key [$LEFT_KEY]: " input && LEFT_KEY="${input:-$LEFT_KEY}"
    read -r -p "Right key [$RIGHT_KEY]: " input && RIGHT_KEY="${input:-$RIGHT_KEY}"
  fi
  check_keys
  save_conf
  if [ "$(cmd_status)" = "installed" ]; then
    render
    common::reload_hyprland
    echo "Configuration updated and applied."
  else
    echo "Configuration saved. Install the improvement to apply it."
  fi
}

case "${1:-}" in
name) cmd_name ;;
description) cmd_description ;;
status) cmd_status ;;
install) cmd_install ;;
uninstall) cmd_uninstall ;;
configure) cmd_configure ;;
*)
  echo "Usage: $0 {name|description|status|install|uninstall|configure}" >&2
  exit 1
  ;;
esac
