// Generated by omarchy-mgldvd. Graphical window to install/uninstall and
// tune the improvements, as an alternative to the terminal menu (./run).
// Launched standalone by ./run-gui (`qs -n -p gui/Main.qml`), without touching
// the main omarchy-shell.
//
// Style: Omarchy-like and flat: monospace font, square corners, wireframe
// (outline-only) buttons. Colors follow the current Omarchy theme
// (~/.local/state/omarchy/current/theme/colors.toml) and update when it changes.
import QtQuick
import QtQuick.Window
import Quickshell
import Quickshell.Io

Window {
  id: win
  visible: true
  width: 560
  height: 640
  minimumWidth: 420
  minimumHeight: 360
  title: "omarchy-mgldvd"
  color: colors.bg

  readonly property string fontFamily: "JetBrainsMono Nerd Font"

  // Defaults are Tokyo Night; applyTheme() overrides them from colors.toml.
  QtObject {
    id: colors
    property color bg: "#1a1b26"
    property color border: "#414868"
    property color text: "#a9b1d6"
    property color bright: "#c0caf5"
    property color muted: "#565f89"
    property color accent: "#7aa2f7"
    property color good: "#9ece6a"
    property color bad: "#f7768e"
  }

  function applyTheme(txt) {
    var t = {};
    txt.split("\n").forEach(function (line) {
      var m = line.match(/^\s*([a-z_]+)\s*=\s*"(#[0-9a-fA-F]{6,8})"/);
      if (m) t[m[1]] = m[2];
    });
    if (t.background) colors.bg = t.background;
    if (t.muted) colors.border = t.muted;
    if (t.foreground) colors.text = t.foreground;
    if (t.bright_foreground) colors.bright = t.bright_foreground;
    if (t.dark_foreground) colors.muted = t.dark_foreground;
    if (t.accent) colors.accent = t.accent;
    if (t.green) colors.good = t.green;
    if (t.red) colors.bad = t.red;
  }

  FileView {
    id: themeFile
    path: Quickshell.env("HOME") + "/.local/state/omarchy/current/theme/colors.toml"
    onLoaded: win.applyTheme(text())
  }

  // The theme directory is swapped when the theme changes, so poll instead of
  // relying on file watching.
  Timer {
    interval: 3000
    running: true
    repeat: true
    onTriggered: themeFile.reload()
  }

  Shortcut {
    sequence: "Escape"
    onActivated: win.quit()
  }
  Shortcut {
    sequence: "Ctrl+Q"
    onActivated: win.quit()
  }

  function quit() {
    win.close();
    Qt.quit();
  }

  // Outline-only ("wireframe") button.
  component WireButton: Rectangle {
    id: btn
    property string label: ""
    property color tone: "#7aa2f7"
    property bool busy: false
    signal clicked

    implicitWidth: lbl.implicitWidth + 24
    implicitHeight: 30
    radius: 0
    color: hover.containsMouse && !btn.busy ? Qt.rgba(tone.r, tone.g, tone.b, 0.16) : "transparent"
    border.color: btn.tone
    border.width: 1
    opacity: btn.busy ? 0.5 : 1.0

    Text {
      id: lbl
      anchors.centerIn: parent
      text: btn.label
      color: btn.tone
      font.family: "JetBrainsMono Nerd Font"
      font.pixelSize: 12
    }
    MouseArea {
      id: hover
      anchors.fill: parent
      hoverEnabled: true
      enabled: !btn.busy
      cursorShape: Qt.PointingHandCursor
      onClicked: btn.clicked()
    }
  }

  readonly property string repoDir: {
    var p = Qt.resolvedUrl(".").toString().replace("file://", "");
    return p.replace(/\/gui\/?$/, "");
  }

  property var improvements: []
  property string busyId: ""
  property string statusMessage: "Loading..."

  function refresh() {
    statusMessage = "Loading...";
    listProc.running = false;
    listProc.running = true;
  }

  Process {
    id: listProc
    command: ["bash", win.repoDir + "/gui/list.sh"]
    stdout: StdioCollector {
      id: listCollector
      onStreamFinished: {
        try {
          win.improvements = JSON.parse(listCollector.text || "[]");
          win.statusMessage = "";
          Qt.callLater(list.positionViewAtBeginning);
        } catch (e) {
          win.statusMessage = "Error reading improvements: " + e;
        }
      }
    }
  }

  Process {
    id: actionProc
    property string pendingId: ""
    stdout: StdioCollector { id: actionOut }
    onRunningChanged: {
      if (!running) {
        win.busyId = "";
        win.statusMessage = actionOut.text ? actionOut.text.trim().split("\n").pop() : "";
        win.refresh();
      }
    }
  }

  function runAction(id, action, extraArgs) {
    var script = win.repoDir + "/improvements/" + id + "/improvement.sh";
    win.busyId = id;
    win.statusMessage = "Running " + action + "...";
    actionProc.command = [script, action].concat(extraArgs || []);
    actionProc.running = false;
    actionProc.running = true;
  }

  Process {
    id: configureProc
    command: ["true"]
  }

  function openConfigure(id) {
    var script = win.repoDir + "/improvements/" + id + "/improvement.sh";
    var inner = "\"" + script + "\" configure; echo; read -p 'Press Enter to close...'";
    configureProc.command = ["foot", "-e", "bash", "-c", inner];
    configureProc.running = false;
    configureProc.running = true;
  }

  Component.onCompleted: refresh()

  Rectangle {
    anchors.fill: parent
    color: colors.bg

    Column {
      anchors.fill: parent
      anchors.margins: 18
      spacing: 14

      Item {
        width: parent.width
        height: headerText.implicitHeight

        Column {
          id: headerText
          anchors.left: parent.left
          anchors.right: closeButton.left
          anchors.rightMargin: 12
          spacing: 2
          Text {
            text: "omarchy-mgldvd"
            color: colors.accent
            font.family: win.fontFamily
            font.pixelSize: 20
            font.bold: true
          }
          Text {
            text: "Mouse and keyboard improvements for Omarchy. Install, uninstall or configure."
            color: colors.muted
            font.family: win.fontFamily
            font.pixelSize: 12
            wrapMode: Text.WordWrap
            width: parent.width
          }
        }

        WireButton {
          id: closeButton
          anchors.right: parent.right
          anchors.top: parent.top
          label: "✕ Close"
          tone: colors.bad
          onClicked: win.quit()
        }
      }

      Rectangle {
        width: parent.width
        height: 1
        color: colors.border
      }

      ListView {
        id: list
        width: parent.width
        height: parent.height - list.y - 30
        spacing: 10
        clip: true
        boundsBehavior: Flickable.StopAtBounds
        model: win.improvements
        delegate: Rectangle {
          id: cardRoot
          property string improvementId: modelData.id
          width: list.width
          height: card.implicitHeight + 24
          radius: 0
          color: "transparent"
          border.color: colors.border
          border.width: 1

          property bool installed: modelData.status === "installed"
          property bool busy: win.busyId === modelData.id

          Column {
            id: card
            anchors.fill: parent
            anchors.margins: 12
            spacing: 8

            Row {
              width: parent.width
              spacing: 8

              Text {
                text: modelData.name
                color: colors.bright
                font.family: win.fontFamily
                font.pixelSize: 14
                font.bold: true
                width: parent.width - badge.width - 8
                wrapMode: Text.WordWrap
              }

              Rectangle {
                id: badge
                radius: 0
                color: "transparent"
                border.color: installed ? colors.good : colors.muted
                border.width: 1
                height: badgeText.implicitHeight + 6
                width: badgeText.implicitWidth + 14
                Text {
                  id: badgeText
                  anchors.centerIn: parent
                  text: installed ? "● installed" : "○ not installed"
                  color: installed ? colors.good : colors.muted
                  font.family: win.fontFamily
                  font.pixelSize: 10
                }
              }
            }

            Text {
              text: modelData.description
              color: colors.text
              font.family: win.fontFamily
              font.pixelSize: 11
              wrapMode: Text.WordWrap
              width: parent.width
            }

            // One slider per numeric option the improvement exposes through the
            // `sliders` subcommand; on release it is applied with `set KEY VALUE`.
            Repeater {
              model: modelData.sliders || []
              delegate: Column {
                id: sl
                width: card.width
                spacing: 4
                property real vMin: modelData.min
                property real vMax: modelData.max
                property real vStep: modelData.step
                property real current: modelData.value

                Text {
                  text: modelData.label + ": " + Math.round(sl.current)
                  color: colors.text
                  font.family: win.fontFamily
                  font.pixelSize: 11
                }

                Item {
                  width: parent.width
                  height: 22

                  // Wireframe track and square handle.
                  Rectangle {
                    anchors.verticalCenter: parent.verticalCenter
                    width: parent.width
                    height: 6
                    radius: 0
                    color: "transparent"
                    border.color: colors.border
                    border.width: 1
                    Rectangle {
                      width: handle.x + handle.width / 2
                      height: parent.height
                      radius: 0
                      color: colors.accent
                      opacity: 0.6
                    }
                  }

                  Rectangle {
                    id: handle
                    width: 14
                    height: 18
                    radius: 0
                    color: colors.bg
                    border.color: colors.accent
                    border.width: 2
                    anchors.verticalCenter: parent.verticalCenter
                    x: (sl.current - sl.vMin) / (sl.vMax - sl.vMin) * (parent.width - width)
                  }

                  MouseArea {
                    anchors.fill: parent
                    enabled: win.busyId === ""
                    cursorShape: Qt.PointingHandCursor
                    function setFromX(mx) {
                      var r = Math.max(0, Math.min(1, (mx - handle.width / 2) / (width - handle.width)));
                      var v = Math.round((sl.vMin + r * (sl.vMax - sl.vMin)) / sl.vStep) * sl.vStep;
                      sl.current = Math.max(sl.vMin, Math.min(sl.vMax, v));
                    }
                    onPressed: mouse => setFromX(mouse.x)
                    onPositionChanged: mouse => { if (pressed) setFromX(mouse.x); }
                    onReleased: win.runAction(cardRoot.improvementId, "set", [modelData.key, String(Math.round(sl.current))])
                  }
                }
              }
            }

            Row {
              spacing: 8

              WireButton {
                label: cardRoot.busy ? "..." : (cardRoot.installed ? "Uninstall" : "Install")
                tone: cardRoot.installed ? colors.bad : colors.good
                busy: cardRoot.busy
                onClicked: win.runAction(modelData.id, cardRoot.installed ? "uninstall" : "install")
              }

              WireButton {
                label: "Configure"
                tone: colors.accent
                busy: cardRoot.busy
                onClicked: win.openConfigure(modelData.id)
              }
            }
          }
        }
      }

      Text {
        width: parent.width
        text: win.statusMessage
        color: colors.muted
        font.family: win.fontFamily
        font.pixelSize: 11
        elide: Text.ElideRight
      }
    }
  }
}
