#!/usr/bin/env bash
# Improvement: the mouse side buttons (back/forward), WITHOUT a modifier,
# switch columns (tiles) in the scrolling layout. At the edge (first/last
# column) one more click stays put, but a DOUBLE click at that same edge
# switches workspace in that direction. Everything works with just the two
# buttons, without needing a third button or a modifier.
# CTRL + back/forward (the mouse-workspace-switch improvement) keeps working
# separately, for a direct workspace switch that doesn't depend on a double
# click.
set -euo pipefail

DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
# shellcheck source=../../lib/common.sh
source "$DIR/../../lib/common.sh"

NAME="mouse-forward-back"
CONF_FILE="$MGLDVD_STATE_DIR/${NAME}.conf"
LUA_FILE="$MGLDVD_HYPR_DIR/${NAME}.lua"
MOVE_SCRIPT="$MGLDVD_STATE_DIR/${NAME}-move.sh"
EDGE_FILE="$MGLDVD_STATE_DIR/${NAME}-edge"

defaults() {
  # Typical evdev codes: BTN_SIDE=275 (back), BTN_EXTRA=276 (forward).
  BACK_BUTTON="275"
  FORWARD_BUTTON="276"
  # Time window (ms) for two consecutive clicks at the same edge to count as
  # a "double click" and switch workspace.
  DOUBLECLICK_MS="450"
}

load_conf() {
  defaults
  # shellcheck disable=SC1090
  [ -f "$CONF_FILE" ] && source "$CONF_FILE"
  return 0
}

save_conf() {
  common::ensure_state_dir
  cat >"$CONF_FILE" <<EOF
BACK_BUTTON="$BACK_BUTTON"
FORWARD_BUTTON="$FORWARD_BUTTON"
DOUBLECLICK_MS="$DOUBLECLICK_MS"
EOF
}

# Always runs as an external process (never io.popen inside a Lua bind): see
# the "Safety rule" in the repo README.
render_move_script() {
  cat >"$MOVE_SCRIPT" <<EOF
#!/usr/bin/env bash
# Generated by omarchy-mgldvd (improvement: ${NAME}). Do not edit by hand.
set -euo pipefail
dir="\$1"
EDGE_FILE="${EDGE_FILE}"
DOUBLECLICK_MS="${DOUBLECLICK_MS}"

if [ "\$dir" = "back" ]; then
  layout_dir="r"
  ws_step=1
else
  layout_dir="l"
  ws_step=-1
fi

before="\$(hyprctl -j activewindow 2>/dev/null | jq -r '.address // empty')"
hyprctl dispatch "hl.dsp.layout(\\"focus \$layout_dir\\")" >/dev/null 2>&1 || true
after="\$(hyprctl -j activewindow 2>/dev/null | jq -r '.address // empty')"

if [ "\$before" != "\$after" ]; then
  # The column changed: any pending double click is now stale.
  rm -f "\$EDGE_FILE"
  exit 0
fi

# There were no more columns in that direction (we are at the edge).
now_ms="\$(date +%s%3N)"
last_ms=""
last_dir=""
if [ -f "\$EDGE_FILE" ]; then
  read -r last_ms last_dir <"\$EDGE_FILE" || true
fi

if [ -n "\$last_ms" ] && [ "\$last_dir" = "\$dir" ] && [ \$((now_ms - last_ms)) -le "\$DOUBLECLICK_MS" ]; then
  # Double click at the edge: now switch workspace, without wrapping.
  rm -f "\$EDGE_FILE"
  current="\$(hyprctl -j activeworkspace 2>/dev/null | jq -r '.id')"
  mapfile -t ids < <(hyprctl -j workspaces 2>/dev/null | jq -r '[.[] | select(.id > 0) | .id] | sort_by(.) | .[]')
  idx=-1
  for i in "\${!ids[@]}"; do
    if [ "\${ids[\$i]}" = "\$current" ]; then
      idx=\$i
      break
    fi
  done
  if [ "\$idx" -ge 0 ]; then
    target=\$((idx + ws_step))
    if [ "\$target" -ge 0 ] && [ "\$target" -lt "\${#ids[@]}" ]; then
      hyprctl dispatch "hl.dsp.focus({ workspace = \\"\${ids[\$target]}\\" })" >/dev/null
    fi
  fi
else
  echo "\$now_ms \$dir" >"\$EDGE_FILE"
fi
EOF
  chmod +x "$MOVE_SCRIPT"
}

render() {
  common::ensure_mgldvd_dir
  common::ensure_state_dir
  render_move_script
  local back_key forward_key
  back_key="$(common::bind_key "" "$BACK_BUTTON")"
  forward_key="$(common::bind_key "" "$FORWARD_BUTTON")"
  cat >"$LUA_FILE" <<EOF
-- Generated by omarchy-mgldvd (improvement: ${NAME}).
-- Do not edit this file by hand: use "./run" in the omarchy-mgldvd repo
-- to adjust the button codes or the double-click time.
o.bind("${back_key}", "Next column / double click at the edge = next workspace", "${MOVE_SCRIPT} back")
o.bind("${forward_key}", "Previous column / double click at the edge = previous workspace", "${MOVE_SCRIPT} forward")
EOF
}

cmd_name() { echo "Mouse: back/forward switch tiles; double click at the edge switches workspace"; }

cmd_description() {
  load_conf
  echo "Back/forward button = next/previous column (mouse:${BACK_BUTTON}/${FORWARD_BUTTON}). At the first/last tile a click stays put; a second click within ${DOUBLECLICK_MS}ms switches workspace."
}

cmd_status() {
  if [ -f "$LUA_FILE" ] && common::require_block_present "$NAME"; then
    echo "installed"
  else
    echo "not-installed"
  fi
}

cmd_install() {
  load_conf
  render
  common::add_require_block "$NAME"
  # Same reason as the other mouse improvements: without this, keyboard focus
  # "bounces" back to the window under the cursor when switching tiles with
  # the mouse (the cursor doesn't move when focus changes).
  common::add_marked_block "$INPUT_FILE" "$NAME" 'hl.config({ input = { follow_mouse = 2 } })'
  save_conf
  common::reload_hyprland
  echo "Installed: mouse:${BACK_BUTTON} (back) / mouse:${FORWARD_BUTTON} (forward). Double click at the edge (< ${DOUBLECLICK_MS}ms) = switch workspace."
  echo "Note: requires the 'scrolling-layout' improvement to be installed."
}

cmd_uninstall() {
  common::remove_require_block "$NAME"
  common::remove_marked_block "$INPUT_FILE" "$NAME"
  rm -f "$LUA_FILE" "$MOVE_SCRIPT" "$EDGE_FILE"
  common::reload_hyprland
  echo "Uninstalled (the follow_mouse setting was reverted too)."
}

cmd_configure() {
  load_conf
  if command -v gum >/dev/null 2>&1; then
    echo "Typical evdev codes: back=275 (BTN_SIDE), forward=276 (BTN_EXTRA)."
    echo "If your mouse uses other codes, check them with 'wev' while pressing the buttons."
    BACK_BUTTON=$(gum input --value "$BACK_BUTTON" --header "'Back' button code")
    FORWARD_BUTTON=$(gum input --value "$FORWARD_BUTTON" --header "'Forward' button code")
    DOUBLECLICK_MS=$(gum input --value "$DOUBLECLICK_MS" --header "Double-click window in milliseconds")
  else
    read -r -p "Back button code [$BACK_BUTTON]: " input && BACK_BUTTON="${input:-$BACK_BUTTON}"
    read -r -p "Forward button code [$FORWARD_BUTTON]: " input && FORWARD_BUTTON="${input:-$FORWARD_BUTTON}"
    read -r -p "Double-click window in ms [$DOUBLECLICK_MS]: " input && DOUBLECLICK_MS="${input:-$DOUBLECLICK_MS}"
  fi
  save_conf
  if [ "$(cmd_status)" = "installed" ]; then
    render
    common::reload_hyprland
    echo "Configuration updated and applied."
  else
    echo "Configuration saved. Install the improvement to apply it."
  fi
}

case "${1:-}" in
name) cmd_name ;;
description) cmd_description ;;
status) cmd_status ;;
install) cmd_install ;;
uninstall) cmd_uninstall ;;
configure) cmd_configure ;;
*)
  echo "Usage: $0 {name|description|status|install|uninstall|configure}" >&2
  exit 1
  ;;
esac
