#!/usr/bin/env bash
# Improvement: marks a range of workspaces (1..N) as "persistent" so they keep
# existing even when empty and not the active workspace.
#
# By default Hyprland destroys an empty workspace as soon as you leave it
# (unless it is persistent), so a workspace that was created but had no apps
# (e.g. "5") vanished from "hyprctl -j workspaces" the moment you left it,
# and mouse-forward-back / mouse-workspace-switch could no longer jump there.
# With persistent=true the workspace is always available.
set -euo pipefail

DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
# shellcheck source=../../lib/common.sh
source "$DIR/../../lib/common.sh"

NAME="persistent-workspaces"
CONF_FILE="$MGLDVD_STATE_DIR/${NAME}.conf"
LUA_FILE="$MGLDVD_HYPR_DIR/${NAME}.lua"

defaults() {
  # Omarchy already binds SUPER+1..0 to workspaces 1-10 by default, so that
  # is the logical range to keep alive.
  COUNT="10"
}

load_conf() {
  defaults
  # shellcheck disable=SC1090
  [ -f "$CONF_FILE" ] && source "$CONF_FILE"
  return 0
}

save_conf() {
  common::ensure_state_dir
  cat >"$CONF_FILE" <<EOF
COUNT="$COUNT"
EOF
}

render() {
  common::ensure_mgldvd_dir
  cat >"$LUA_FILE" <<EOF
-- Generated by omarchy-mgldvd (improvement: ${NAME}).
-- Do not edit this file by hand: use "./run" in the omarchy-mgldvd repo
-- to adjust how many workspaces are always kept alive.
for i = 1, ${COUNT} do
  hl.workspace_rule({ workspace = tostring(i), persistent = true })
end
EOF
}

cmd_name() { echo "Workspaces: keep 1..N always alive (even when empty)"; }

cmd_description() {
  load_conf
  echo "Workspaces 1 to ${COUNT} stay 'persistent': they are not destroyed when empty, so the mouse (double click at the edge) or SUPER+number can always jump there."
}

cmd_status() {
  if [ -f "$LUA_FILE" ] && common::require_block_present "$NAME" "$LOOKNFEEL_FILE"; then
    echo "installed"
  else
    echo "not-installed"
  fi
}

cmd_install() {
  load_conf
  render
  common::add_require_block "$NAME" "$LOOKNFEEL_FILE"
  save_conf
  common::reload_hyprland
  echo "Installed: workspaces 1 to ${COUNT} marked as persistent."
}

cmd_uninstall() {
  common::remove_require_block "$NAME" "$LOOKNFEEL_FILE"
  rm -f "$LUA_FILE"
  common::reload_hyprland
  echo "Uninstalled (empty workspaces will be destroyed again when you leave them)."
}

cmd_configure() {
  load_conf
  if command -v gum >/dev/null 2>&1; then
    COUNT=$(gum input --value "$COUNT" --header "How many workspaces to keep always alive (starting at 1)")
  else
    read -r -p "Number of persistent workspaces [$COUNT]: " input && COUNT="${input:-$COUNT}"
  fi
  save_conf
  if [ "$(cmd_status)" = "installed" ]; then
    render
    common::reload_hyprland
    echo "Configuration updated and applied."
  else
    echo "Configuration saved. Install the improvement to apply it."
  fi
}

case "${1:-}" in
name) cmd_name ;;
description) cmd_description ;;
status) cmd_status ;;
install) cmd_install ;;
uninstall) cmd_uninstall ;;
configure) cmd_configure ;;
*)
  echo "Usage: $0 {name|description|status|install|uninstall|configure}" >&2
  exit 1
  ;;
esac
