#!/usr/bin/env bash
# Improvement: switches Hyprland's native tiling layout from "dwindle" (tree)
# to "scrolling" (niri/PaperWM style): windows are laid out on a strip that
# extends to one side and can go past the viewport; you can keep opening
# applications toward that side and the view scrolls horizontally to show them.
set -euo pipefail

DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
# shellcheck source=../../lib/common.sh
source "$DIR/../../lib/common.sh"

NAME="scrolling-layout"
CONF_FILE="$MGLDVD_STATE_DIR/${NAME}.conf"
LUA_FILE="$MGLDVD_HYPR_DIR/${NAME}.lua"

defaults() {
  DIRECTION="right"
  COLUMN_WIDTH="0.5"
  # false: reaching the last column does not wrap to the first (and vice versa).
  WRAP_FOCUS="false"
}

load_conf() {
  defaults
  # shellcheck disable=SC1090
  [ -f "$CONF_FILE" ] && source "$CONF_FILE"
  return 0
}

save_conf() {
  common::ensure_state_dir
  cat >"$CONF_FILE" <<EOF
DIRECTION="$DIRECTION"
COLUMN_WIDTH="$COLUMN_WIDTH"
WRAP_FOCUS="$WRAP_FOCUS"
EOF
}

render() {
  common::ensure_mgldvd_dir
  cat >"$LUA_FILE" <<EOF
-- Generated by omarchy-mgldvd (improvement: ${NAME}).
-- Do not edit this file by hand: use "./run" in the omarchy-mgldvd repo
-- to adjust the direction, the column width or the wrap.
hl.config({
  general = { layout = "scrolling" },
  scrolling = {
    direction = "${DIRECTION}",
    column_width = ${COLUMN_WIDTH},
    wrap_focus = ${WRAP_FOCUS},
  },
})
EOF
}

cmd_name() { echo "Layout: windows on a horizontal strip (scrolling, niri/PaperWM style)"; }

cmd_description() {
  load_conf
  local wrap_label="no wrap"
  [ "$WRAP_FOCUS" = "true" ] && wrap_label="wraps around"
  echo "Replaces dwindle with the native 'scrolling' layout: windows line up toward '${DIRECTION}', can go past the viewport, and the view scrolls to show them. Column width: ${COLUMN_WIDTH}, ${wrap_label}."
}

cmd_status() {
  if [ -f "$LUA_FILE" ] && common::require_block_present "$NAME" "$LOOKNFEEL_FILE"; then
    echo "installed"
  else
    echo "not-installed"
  fi
}

cmd_install() {
  load_conf
  render
  common::add_require_block "$NAME" "$LOOKNFEEL_FILE"
  save_conf
  common::reload_hyprland
  echo "Installed: 'scrolling' layout, direction=${DIRECTION}, column_width=${COLUMN_WIDTH}."
  echo "Note: the mouse improvements that move between columns work best with this one installed."
}

cmd_uninstall() {
  common::remove_require_block "$NAME" "$LOOKNFEEL_FILE"
  rm -f "$LUA_FILE"
  common::reload_hyprland
  echo "Uninstalled (back to the default 'dwindle' layout)."
}

cmd_configure() {
  load_conf
  if command -v gum >/dev/null 2>&1; then
    DIRECTION=$(gum choose --header "Direction the strip extends toward" "right" "left" "down" "up")
    COLUMN_WIDTH=$(gum input --value "$COLUMN_WIDTH" --header "Column width (0.1 to 1.0; 0.5 = half the screen)")
    local wrap_choice
    wrap_choice=$(gum choose --header "When reaching the last/first column" \
      "Don't wrap (stay at the edge)" "Wrap (go to the other edge)")
    if [ "$wrap_choice" = "Wrap (go to the other edge)" ]; then
      WRAP_FOCUS="true"
    else
      WRAP_FOCUS="false"
    fi
  else
    read -r -p "Direction (right/left/down/up) [$DIRECTION]: " input && DIRECTION="${input:-$DIRECTION}"
    read -r -p "Column width [$COLUMN_WIDTH]: " input && COLUMN_WIDTH="${input:-$COLUMN_WIDTH}"
    read -r -p "Wrap at the edges true/false [$WRAP_FOCUS]: " input && WRAP_FOCUS="${input:-$WRAP_FOCUS}"
  fi
  save_conf
  if [ "$(cmd_status)" = "installed" ]; then
    render
    common::reload_hyprland
    echo "Configuration updated and applied."
  else
    echo "Configuration saved. Install the improvement to apply it."
  fi
}

case "${1:-}" in
name) cmd_name ;;
description) cmd_description ;;
status) cmd_status ;;
install) cmd_install ;;
uninstall) cmd_uninstall ;;
configure) cmd_configure ;;
*)
  echo "Usage: $0 {name|description|status|install|uninstall|configure}" >&2
  exit 1
  ;;
esac
