#!/usr/bin/env bash
# Improvement: the mouse side buttons (back/forward) plus a modifier switch
# workspace, like the browser's back/forward.
set -euo pipefail

DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
# shellcheck source=../../lib/common.sh
source "$DIR/../../lib/common.sh"

NAME="mouse-workspace-switch"
CONF_FILE="$MGLDVD_STATE_DIR/${NAME}.conf"
LUA_FILE="$MGLDVD_HYPR_DIR/${NAME}.lua"
NOWRAP_SCRIPT="$MGLDVD_STATE_DIR/${NAME}-nowrap.sh"

defaults() {
  # Typical evdev codes for a mouse with side buttons:
  # BTN_SIDE=275 (back), BTN_EXTRA=276 (forward).
  MODIFIER="CTRL"
  BACK_BUTTON="275"
  FORWARD_BUTTON="276"
}

load_conf() {
  defaults
  # shellcheck disable=SC1090
  [ -f "$CONF_FILE" ] && source "$CONF_FILE"
  return 0
}

save_conf() {
  common::ensure_state_dir
  cat >"$CONF_FILE" <<EOF
MODIFIER="$MODIFIER"
BACK_BUTTON="$BACK_BUTTON"
FORWARD_BUTTON="$FORWARD_BUTTON"
EOF
}

render_nowrap_script() {
  cat >"$NOWRAP_SCRIPT" <<'EOS'
#!/usr/bin/env bash
# Generated by omarchy-mgldvd. Do not edit by hand.
# Hyprland has no flag to stop "e+1"/"e-1" from wrapping around at the
# first/last workspace (the wiki explicitly says that selector "wraps
# around"), so the workspace list is walked by hand and nothing happens if
# we are already at the edge. It runs as an external process (never
# io.popen inside a Lua bind) so it doesn't block Hyprland's main thread
# waiting on its own IPC socket.
set -euo pipefail
step="$1"
current="$(hyprctl -j activeworkspace 2>/dev/null | jq -r '.id')"
mapfile -t ids < <(hyprctl -j workspaces 2>/dev/null | jq -r '[.[] | select(.id > 0) | .id] | sort_by(.) | .[]')
idx=-1
for i in "${!ids[@]}"; do
  if [ "${ids[$i]}" = "$current" ]; then
    idx=$i
    break
  fi
done
[ "$idx" -ge 0 ] || exit 0
target=$((idx + step))
[ "$target" -ge 0 ] && [ "$target" -lt "${#ids[@]}" ] || exit 0
hyprctl dispatch "hl.dsp.focus({ workspace = \"${ids[$target]}\" })" >/dev/null
EOS
  chmod +x "$NOWRAP_SCRIPT"
}

render() {
  common::ensure_mgldvd_dir
  render_nowrap_script
  cat >"$LUA_FILE" <<EOF
-- Generated by omarchy-mgldvd (improvement: ${NAME}).
-- Do not edit this file by hand: use "./run" in the omarchy-mgldvd repo
-- to adjust the modifier or the button codes.
o.bind("${MODIFIER} + mouse:${BACK_BUTTON}", "Next workspace (mouse back button)", "${NOWRAP_SCRIPT} 1")
o.bind("${MODIFIER} + mouse:${FORWARD_BUTTON}", "Previous workspace (mouse forward button)", "${NOWRAP_SCRIPT} -1")
EOF
}

cmd_name() { echo "Mouse: side buttons switch workspace"; }

cmd_description() {
  load_conf
  echo "${MODIFIER} + mouse back/forward button = next/previous workspace (mouse:${BACK_BUTTON}/mouse:${FORWARD_BUTTON})."
}

cmd_status() {
  if [ -f "$LUA_FILE" ] && common::require_block_present "$NAME"; then
    echo "installed"
  else
    echo "not-installed"
  fi
}

cmd_install() {
  load_conf
  render
  common::add_require_block "$NAME"
  save_conf
  common::reload_hyprland
  echo "Installed: ${MODIFIER} + mouse:${BACK_BUTTON} (back) / mouse:${FORWARD_BUTTON} (forward)."
}

cmd_uninstall() {
  common::remove_require_block "$NAME"
  rm -f "$LUA_FILE" "$NOWRAP_SCRIPT"
  common::reload_hyprland
  echo "Uninstalled."
}

cmd_configure() {
  load_conf
  if command -v gum >/dev/null 2>&1; then
    MODIFIER=$(gum choose --header "Modifier for the side buttons" \
      "CTRL" "ALT" "SUPER" "SHIFT" "CTRL + ALT" "CTRL + SHIFT")
    echo "Typical evdev codes: back=275 (BTN_SIDE), forward=276 (BTN_EXTRA)."
    echo "If your mouse uses other codes, check them with 'libinput debug-events' or 'wev'."
    BACK_BUTTON=$(gum input --value "$BACK_BUTTON" --header "'Back' button code")
    FORWARD_BUTTON=$(gum input --value "$FORWARD_BUTTON" --header "'Forward' button code")
  else
    read -r -p "Modifier [$MODIFIER]: " input && MODIFIER="${input:-$MODIFIER}"
    read -r -p "Back button code [$BACK_BUTTON]: " input && BACK_BUTTON="${input:-$BACK_BUTTON}"
    read -r -p "Forward button code [$FORWARD_BUTTON]: " input && FORWARD_BUTTON="${input:-$FORWARD_BUTTON}"
  fi
  save_conf
  if [ "$(cmd_status)" = "installed" ]; then
    render
    common::reload_hyprland
    echo "Configuration updated and applied."
  else
    echo "Configuration saved. Install the improvement to apply it."
  fi
}

case "${1:-}" in
name) cmd_name ;;
description) cmd_description ;;
status) cmd_status ;;
install) cmd_install ;;
uninstall) cmd_uninstall ;;
configure) cmd_configure ;;
*)
  echo "Usage: $0 {name|description|status|install|uninstall|configure}" >&2
  exit 1
  ;;
esac
